### ISSUE TITLE
How to configure a map rotation through maps in northstar

### ISSUE THREAD

**Issue by jamesla** [pg9182/northstar-dedicated#103]
Given the following how do I give it a set of maps to rotate through, while staying in gungame??

Currently when the map ends it switches to attrition

```yaml
---
version: '3'
services:
  titanfall2-gungame:
    image: ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0
    pull_policy: always
    environment:
      - NS_PORT=37015
      - NS_SERVER_NAME=Test
      - |
        NS_EXTRA_ARGUMENTS=
          +setplaylist private_match 
          +mp_gamemode gg
          +map mp_glitch
          +ns_should_return_to_lobby 0
          +net_compresspackets_minsize 64
          +net_compresspackets 1
          +spewlog_enable 0
          +sv_maxrate 127000
          +ns_auth_allow_insecure 1
    volumes:
      - /home/james/Titanfall2:/mnt/titanfall:ro
      - /home/james/Titanfall2/mods:/mnt/mods:ro
    ports:
      - '37015:37015/udp'
```
