### ISSUE TITLE
Crash when no volume is mounted to /mnt/save_data

### ISSUE THREAD

**Issue by Legonzaur** [pg9182/northstar-dedicated#62]
After d292bf6e80e23e4e39d0ff06a7c0f3dcf7d0021c, when launching a container without mounting any directory to `/mnt/save_data`, the container cannot start.

`Error: Failed to merge game files: merge save data: access "/mnt/save_data": stat /mnt/save_data: no such file or directory.`

Minimalistic docker-compose.yml as an example : 
```yml
version: "3.1"

services:

  northstar:
    image: ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0
    pull_policy: always
    volumes:
      - /opt/Titanfall2:/mnt/titanfall:ro
      # - ./test:/mnt/save_data:rw
    environment:
      - 'NS_SERVER_NAME=your server name'
      - 'NS_SERVER_DESC=your server description'
```
