### ISSUE TITLE
Container crashes when trying to write file

### ISSUE THREAD

**Issue by Legonzaur** [pg9182/northstar-dedicated#63]
When trying to write in a file using `NSSaveFile`, container kills itself unpromptedly

```cpp
void function SavePlayerCount(){
    NSSaveFile("playerCount.txt", file.playerCount.tostring())
}
```

```yml
version: "3.1"

services:

  northstar:
    image: ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0
    ports:
      - '37015:37015/udp'
    volumes:
      - ./Titanfall2:/mnt/titanfall:ro
      - ./test:/mnt/save_data:rw
      - ./NorthstarPlayerCount:/mnt/mods/NorthstarPlayerCount:ro
    environment:
      - 'NS_SERVER_NAME=your server name'
      - 'NS_SERVER_DESC=your server description'
      - 'NS_MASTERSERVER_REGISTER=0'
      - 'NS_INSECURE=1'
```

![image](https://github.com/pg9182/northstar-dedicated/assets/34353603/3cc00e76-ac62-4799-834a-a7805d67459d)
